import {beforeAll,beforeEach,afterAll,test,expect} from 'bun:test';
import {PGlite} from '@electric-sql/pglite';
import {pgliteAdapter} from './pglite-adapter.ts';
import {initApplicationSettings,handleApplicationSettings,handleProphylaxisConfiguration,APPLICATION_DEFAULTS} from '../settings.ts';
import {calculatePaspIndicators} from '../pasp.ts';
let db:any,sql:any;
beforeAll(async()=>{db=new PGlite();sql=pgliteAdapter(db);await initApplicationSettings(sql);await sql.unsafe('create table qx_simulation.qx_prophylaxis_rules(row_order integer primary key,payload jsonb,updated_at timestamptz default now())');});
beforeEach(async()=>{await sql.unsafe("update qx_simulation.qx_application_settings set version=1,payload=$1::jsonb where id='PAGE'",[JSON.stringify(APPLICATION_DEFAULTS)]);await sql.unsafe('truncate qx_simulation.qx_application_settings_history,qx_simulation.qx_prophylaxis_rules');});
afterAll(async()=>db.close());
async function call(path:string,body?:any,role='SUPERADMIN'){const url=new URL('https://example.invalid'+path),req=new Request(url,{method:body?'POST':'GET',...(body?{body:JSON.stringify(body),headers:{'content-type':'application/json'}}:{})}),ctx={sql,session:role?{role,user:'SIM-ADMIN'}:null,json:(b:any,status=200)=>Response.json(b,{status})};const response=path.includes('prophylaxis-rules')?await handleProphylaxisConfiguration(req,url,ctx):await handleApplicationSettings(req,url,ctx);return {status:response!.status,body:await response!.json()};}
test('presentación pública no expone listas internas ni configuración administrativa',async()=>{const r=await call('/api/application-settings/public',undefined,'');expect(r.status).toBe(200);expect(r.body.branding.portalRefreshSeconds).toBe(15);expect(r.body.lists).toBeUndefined();expect((await call('/api/application-settings',undefined,'')).status).toBe(401)});
test('catálogo contiene 71 indicadores separados y 19 reportes agregados',async()=>{const r=await call('/api/indicator-definitions');expect(r.body.metrics.length).toBe(71);expect(r.body.aggregateReports.length).toBe(19);expect(r.body.metrics.filter((m:any)=>m.scope==='INSTITUCIONAL').length).toBe(23)});
test('listas, metas y etiquetas se guardan con versión y autor sin tocar datos clínicos',async()=>{const config=structuredClone(APPLICATION_DEFAULTS);config.lists.fEsp.push('ESPECIALIDAD FICTICIA');config.indicatorMetadata={PASP_FIRST_CALL_COVERAGE:{label:'Cobertura ficticia',goal:'≥92%'}};const saved=await call('/api/application-settings',{expectedVersion:1,config,reason:'Ajuste SIMULADO QA'});expect(saved.status).toBe(200);expect(saved.body.version).toBe(2);const defs=await call('/api/indicator-definitions');expect(defs.body.metrics.find((m:any)=>m.id==='PASP_FIRST_CALL_COVERAGE').goal).toBe('≥92%');const stale=await call('/api/application-settings',{expectedVersion:1,config,reason:'Reintento'});expect(stale.status).toBe(409);expect((await sql.unsafe('select payload from qx_simulation.qx_application_settings_history')).length).toBe(1)});
test('solo SUPERADMIN configura y el denominador no cambia al editar una meta',async()=>{const config=structuredClone(APPLICATION_DEFAULTS);expect((await call('/api/application-settings',{expectedVersion:1,config,reason:'QA'},'ADMIN')).status).toBe(403);config.indicatorMetadata={PASP_FIRST_CALL_COVERAGE:{formula:'formula alterada'}} as any;expect((await call('/api/application-settings',{expectedVersion:1,config,reason:'QA'})).status).toBe(400)});
test('validación rechaza listas duplicadas, color inválido y actualización excesiva',async()=>{for(const change of [(p:any)=>p.lists.fEsp.push(p.lists.fEsp[0]),(p:any)=>p.branding.primaryColor='javascript:alert(1)',(p:any)=>p.branding.portalRefreshSeconds=0]){const config=structuredClone(APPLICATION_DEFAULTS);change(config);expect((await call('/api/application-settings',{expectedVersion:1,config,reason:'QA'})).status).toBe(400)}});
test('el plazo configurable de cita POP modifica el cálculo y no la historia del paciente',()=>{const episode={id:'SIM',sourceKind:'SIMULADO',surgeryDate:'2026-10-01',patientStatus:'Ambulatorio',appointment:{date:'2026-10-14',status:'Programada'}};const a=calculatePaspIndicators([episode],[],[]),b=calculatePaspIndicators([episode],[],[],{},undefined,{appointmentMaxDays:14});expect(a.metrics.find((m:any)=>m.id==='appointment_timeliness').value).toBe(0);expect(b.metrics.find((m:any)=>m.id==='appointment_timeliness').value).toBe(100);expect(episode.appointment.date).toBe('2026-10-14')});
test('una regla de profilaxis activa exige fuente, versión y revisión institucional',async()=>{const rule={ESPECIALIDAD:'ESPECIALIDAD SIMULADA',PROCEDIMIENTO:'PROCEDIMIENTO SIMULADO',ESTADO:'ACTIVO',APROBACION:'PENDIENTE'};expect((await call('/api/prophylaxis-rules',{rule,reason:'QA'})).status).toBe(400);rule.ESTADO='INACTIVO';const saved=await call('/api/prophylaxis-rules',{rule,reason:'Protocolo ficticio sin prescripción'});expect(saved.status).toBe(200);expect(saved.body.rule['VERSIÓN CONFIG']).toBe(1);const denied=await call('/api/prophylaxis-rules',{rule,reason:'QA'},'USER');expect(denied.status).toBe(403)});
