import postgres from "postgres";
import { createHash, createHmac, timingSafeEqual, randomUUID, randomBytes } from "node:crypto";
const dbUrl=Bun.env.DATABASE_URL;if(!dbUrl)throw new Error("DATABASE_URL missing");
const sql=postgres(dbUrl,{ssl:"require",max:8});const PORT=Number(Bun.env.PORT||3000),SESSION_TTL=21600000;
const sessionKey=createHash("sha256").update(dbUrl+"|APP_WEB_CX_SESSION").digest();const PAGE=await Bun.file("./public/index.html").text();
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:Object.assign({"content-type":"application/json; charset=utf-8","cache-control":"no-store"},headers)})}
function html(body,status=200){return new Response(body,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})}
function b64(v){return Buffer.from(v).toString("base64url")}function sign(p){const b=b64(JSON.stringify(p));return b+"."+createHmac("sha256",sessionKey).update(b).digest("base64url")}
function verify(t){try{const [b,s]=String(t||"").split(".");if(!b||!s)return null;const e=createHmac("sha256",sessionKey).update(b).digest(),g=Buffer.from(s,"base64url");if(e.length!==g.length||!timingSafeEqual(e,g))return null;const p=JSON.parse(Buffer.from(b,"base64url").toString("utf8"));return p.exp&&Date.now()<p.exp?p:null}catch{return null}}
function cookies(req){const o={};(req.headers.get("cookie")||"").split(";").forEach(x=>{const i=x.indexOf("=");if(i>0)o[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim())});return o}
function sess(req){return verify(cookies(req).qx_session||"")}function sha(v){return createHash("sha256").update(String(v||"")).digest("hex")}
function secureHash(pin,salt,pepper){let acc=String(pin||"")+"|"+String(salt||"");for(let i=0;i<600;i++)acc=createHmac("sha256",pepper+"|"+salt+"|"+i).update(acc).digest("hex");return acc}
function eqHex(a,b){try{const x=Buffer.from(String(a||""),"hex"),y=Buffer.from(String(b||""),"hex");return x.length===y.length&&timingSafeEqual(x,y)}catch{return false}}
function safeDate(s){return /^\d{4}-\d{2}-\d{2}$/.test(s||"")?s:new Date().toLocaleDateString("en-CA",{timeZone:"America/Bogota"})}
function norm(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toUpperCase()}
function nowBog(){return new Date().toLocaleString("sv-SE",{timeZone:"America/Bogota"}).replace("T"," ")}
function monthName(n){return ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"][n-1]||""}
async function body(req){try{return await req.json()}catch{return {}}}
function mapCase(p){return {id:p["ID CASO"]||"",fecha:p["FECHA CIRUGÍA"]||"",hora:p["HORA PROGRAMADA"]||"",documento:p["DOCUMENTO"]||"",paciente:p["PACIENTE"]||"",edad:p["EDAD"]||"",sexo:p["SEXO"]||"",procedimiento:p["PROCEDIMIENTO"]||"",especialidad:p["ESPECIALIDAD"]||"",especialista:p["ESPECIALISTA"]||"",qno:p["SALA / QNO"]||"",estado:String(p["ESTADO ACTUAL"]||"PROGRAMADO").toUpperCase(),observaciones:p["OBSERVACIONES"]||"",tipoAtencion:p["TIPO DE ATENCIÓN"]||"",operado:["TRUE","SI","SÍ","1"].includes(norm(p["OPERADO"])),destino:p["DESTINO POSTOP"]||"",salida:p["HORA SALIDA RECUPERACIÓN"]||"",observacionEgreso:p["OBSERVACIÓN EGRESO / HOSPITALIZACIÓN"]||"",codigo:p["CÓDIGO SEGUIMIENTO"]||"",token:p["TOKEN SEGUIMIENTO"]||"",actualizado:p["ÚLTIMA ACTUALIZACIÓN WEB"]||p["FECHA/HORA ÚLTIMO MOVIMIENTO"]||"",tPrepa:Number(p["TIEMPO PREPA → QNO (MIN)"]||0)||0,tQnoRec:Number(p["TIEMPO QNO → RECUPERACIÓN (MIN)"]||0)||0,tMuerto:Number(p["INTERVALO ENTRE PACIENTES QNO (MIN)"]||0)||0,prof:p["PROFILAXIS ADMINISTRADA"]||"",profHora:p["HORA ADMINISTRACIÓN PROFILAXIS"]||"",profMin:p["PROFILAXIS → INCISIÓN (MIN)"]||"",clasif:p["CLASIFICACIÓN CIRUGÍA"]||"",antibiotico:p["PROFILAXIS ANTIBIÓTICA / MEDICAMENTO"]||"",cups:p["CUPS"]||"",uvr:p["UVR"]||"",tiempoQx:p["TIEMPO QX ESTIMADO (MIN)"]||"",recursos:p["RECURSOS / ALERTAS PREQUIRÚRGICAS"]||"",cama:p["CAMA / UBICACIÓN PROGRAMADA"]||""}}
async function casesFor(date){const d=safeDate(date);const r=await sql.unsafe("select payload from source_sheets where source_key='MAIN' and sheet_name='BD PROGRAMACIÓN' and payload->>'FECHA CIRUGÍA'=$1 order by payload->>'HORA PROGRAMADA'",[d]);return r.map(x=>mapCase(x.payload))}
function metrics(rows){const m={total:rows.length,programado:0,preparacion:0,quirofano:0,recuperacion:0,finalizados:0,cancelados:0,operados:0};rows.forEach(r=>{if(r.estado==="PROGRAMADO")m.programado++;if(r.estado==="PREPARACIÓN")m.preparacion++;if(r.estado==="QUIRÓFANO")m.quirofano++;if(r.estado==="RECUPERACIÓN")m.recuperacion++;if(["ALTA","HOSPITALIZACIÓN"].includes(r.estado)||["ALTA","HOSPITALIZACIÓN"].includes(norm(r.destino)))m.finalizados++;if(r.estado==="CANCELADO")m.cancelados++;if(r.operado)m.operados++});return m}
async function nextRow(sheet){const r=await sql.unsafe("select coalesce(max(row_number),1)+1 as n from source_sheets where source_key='MAIN' and sheet_name=$1",[sheet]);return Number(r[0].n||2)}
async function findCase(id){const r=await sql.unsafe("select row_number,payload from source_sheets where source_key='MAIN' and sheet_name='BD PROGRAMACIÓN' and payload->>'ID CASO'=$1 limit 1",[id]);return r[0]||null}
async function audit(s,action,module,id,detail,result="OK"){try{const rn=await nextRow("LOG AUDITORÍA");const p={"MARCA TEMPORAL":nowBog(),"USUARIO":s?.user||"SISTEMA","ROL":s?.role||"SISTEMA","ACCIÓN":action,"ID CASO":id||"","MÓDULO":module,"DETALLE":detail||"","RESULTADO":result,"VERSIÓN":"RAILWAY-5"};await sql.unsafe("insert into source_sheets(source_key,spreadsheet_id,spreadsheet_title,sheet_name,row_number,payload) values('MAIN','RAILWAY','Railway operational','LOG AUDITORÍA',$1,$2::jsonb)",[rn,JSON.stringify(p)])}catch{}}
async function outbox(entity,id,action,payload){try{await sql.unsafe("insert into sync_outbox(entity_type,entity_id,action,payload) values($1,$2,$3,$4::jsonb)",[entity,id||"",action,JSON.stringify(payload)])}catch{}}
async function updateCase(s,id,patch,action){const hit=await findCase(id);if(!hit)throw new Error("Paciente no encontrado.");const old=hit.payload,p=Object.assign({},old,patch,{"FECHA/HORA ÚLTIMO MOVIMIENTO":nowBog(),"USUARIO ÚLTIMO MOVIMIENTO":s.user||"Railway","ÚLTIMA ACTUALIZACIÓN WEB":nowBog(),"ESTADO ANTERIOR":old["ESTADO ACTUAL"]||""});await sql.unsafe("update source_sheets set payload=$1::jsonb,imported_at=now() where source_key='MAIN' and sheet_name='BD PROGRAMACIÓN' and row_number=$2",[JSON.stringify(p),hit.row_number]);await outbox("PACIENTE",id,action,p);await audit(s,action,"OPERACIÓN",id,JSON.stringify(patch));return mapCase(p)}
async function addMovement(s,p,from,to){const rn=await nextRow("HISTORIAL MOVIMIENTOS");const row={"MARCA TEMPORAL":nowBog(),"ID CASO":p["ID CASO"]||"","DOCUMENTO":p["DOCUMENTO"]||"","PACIENTE":p["PACIENTE"]||"","ORIGEN":from||"","DESTINO":to||"","USUARIO":s.user||"","ROL":s.role||"","QNO":p["SALA / QNO"]||"","OBSERVACIÓN":"Railway"};await sql.unsafe("insert into source_sheets(source_key,spreadsheet_id,spreadsheet_title,sheet_name,row_number,payload) values('MAIN','RAILWAY','Railway operational','HISTORIAL MOVIMIENTOS',$1,$2::jsonb)",[rn,JSON.stringify(row)])}
function pct(a,b){return b?Math.round(a*1000/b)/10:0}function avg(a){const x=a.filter(n=>Number.isFinite(n)&&n>0);return x.length?Math.round(x.reduce((s,n)=>s+n,0)*10/x.length)/10:0}
function publicState(s,d){s=norm(s);d=norm(d);if(s==="PREPARACION")return"En preparación prequirúrgica";if(s==="QUIROFANO")return"En procedimiento quirúrgico";if(s==="RECUPERACION")return"En recuperación postanestésica";if(s==="CANCELADO")return"Procedimiento cancelado";if(s==="ALTA"||d==="ALTA")return"Proceso quirúrgico finalizado · Alta";if(s==="HOSPITALIZACION"||d==="HOSPITALIZACION")return"Proceso quirúrgico finalizado · Hospitalización";return"Programado / pendiente de ingreso"}
function maskName(n){const p=String(n||"").trim().split(/\s+/).filter(Boolean);return p.length?p[0]+" "+p.slice(1).map(x=>x[0]+".").join(" "):"Paciente"}
function csvCell(v){const s=String(v??"");return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
Bun.serve({port:PORT,async fetch(req){
 const url=new URL(req.url);if(url.pathname==="/health")return json({ok:true});if(url.pathname==="/")return html(PAGE);
 if(url.pathname==="/api/tracking"){const code=String(url.searchParams.get("code")||"").trim();if(code.length<4)return json({error:"Código inválido."},400);const r=await sql.unsafe("select payload from source_sheets where source_key='MAIN' and sheet_name='BD PROGRAMACIÓN' and ((payload->>'CÓDIGO SEGUIMIENTO')=$1 or (payload->>'TOKEN SEGUIMIENTO')=$1) limit 1",[code]);if(!r.length)return json({error:"No se encontró un caso asociado a ese código."},404);const c=mapCase(r[0].payload);return json({paciente:maskName(c.paciente),estadoPublico:publicState(c.estado,c.destino),actualizado:c.actualizado})}
 if(url.pathname==="/api/login"&&req.method==="POST"){const b=await body(req),u=String(b.user||"").trim().toLowerCase(),pin=String(b.pin||"");const r=await sql.unsafe("select payload from source_sheets where source_key='MAIN' and sheet_name='USUARIOS' and lower(payload->>'USUARIO')=$1 limit 1",[u]);if(!r.length)return json({error:"Usuario o PIN incorrectos."},401);const x=r[0].payload;if(norm(x["ESTADO"])!=="ACTIVO")return json({error:"Cuenta inactiva."},403);const hash=String(x["HASH PIN"]||""),salt=String(x["SALT PIN"]||"");let ok=!salt?eqHex(sha(pin),hash):false;if(salt){const pepper=Bun.env.QX_AUTH_PEPPER_V1||"";if(!pepper)return json({error:"Esta cuenta requiere trasladar QX_AUTH_PEPPER_V1 desde Apps Script."},409);ok=eqHex(secureHash(pin,salt,pepper),hash)}if(!ok)return json({error:"Usuario o PIN incorrectos."},401);const p={uid:x["ID USUARIO"],user:x["USUARIO"],name:x["NOMBRE"],role:x["ROL"],exp:Date.now()+SESSION_TTL},t=sign(p);return json({ok:true,user:p.user,name:p.name,role:p.role},200,{"set-cookie":"qx_session="+encodeURIComponent(t)+"; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=21600"})}
 if(url.pathname==="/api/logout"&&req.method==="POST")return json({ok:true},200,{"set-cookie":"qx_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0"});
 if(url.pathname==="/api/attachment"&&req.method==="POST"){
   const s=sess(req);if(!s)return json({error:"Sesión no autorizada o vencida."},401);
   const fd=await req.formData(),f=fd.get("file");
   if(!(f instanceof File))return json({error:"No se recibió un archivo válido."},400);
   const max=25*1024*1024;if(f.size>max)return json({error:"El archivo supera el límite de 25 MB."},413);
   const caseId=String(fd.get("caseId")||""),context=String(fd.get("context")||"GENERAL").slice(0,80);
   let metadata={};try{metadata=JSON.parse(String(fd.get("metadata")||"{}"))}catch{}
   const buf=Buffer.from(await f.arrayBuffer()),digest=createHash("sha256").update(buf).digest("hex"),id=randomUUID();
   await sql.unsafe("insert into case_attachments(id,case_id,upload_context,original_name,mime_type,size_bytes,sha256,content_base64,metadata,uploaded_by) values($1::uuid,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10)",[id,caseId,context,String(f.name||"archivo").slice(0,255),String(f.type||"application/octet-stream").slice(0,150),f.size,digest,buf.toString("base64"),JSON.stringify(metadata||{}),s.user||""]);
   await audit(s,"CARGA ARCHIVO","ARCHIVOS",caseId,String(f.name||"archivo")+" · "+f.size+" bytes");
   return json({ok:true,id,caseId,context,name:f.name,type:f.type||"application/octet-stream",size:f.size,sha256:digest});
 }
 const s=sess(req);if(!s)return json({error:"Sesión no autorizada o vencida."},401);if(url.pathname==="/api/me")return json({valid:true,user:s.user,name:s.name,role:s.role});
 if(url.pathname==="/api/board"){const rows=await casesFor(url.searchParams.get("date")||"");return json({rows,metrics:metrics(rows)})}
 if(url.pathname==="/api/case/move"&&req.method==="POST"){const b=await body(req),hit=await findCase(b.id);if(!hit)return json({error:"Paciente no encontrado."},404);const from=String(hit.payload["ESTADO ACTUAL"]||"PROGRAMADO").toUpperCase(),to=String(b.destino||"").toUpperCase();const allowed={PROGRAMADO:["PREPARACIÓN","QUIRÓFANO"],"PREPARACIÓN":["PROGRAMADO","QUIRÓFANO"],"QUIRÓFANO":["PREPARACIÓN","RECUPERACIÓN"],"RECUPERACIÓN":["ALTA","HOSPITALIZACIÓN"]};if(!(allowed[from]||[]).includes(to))return json({error:"Transición no permitida: "+from+" → "+to},409);const patch={"ESTADO ACTUAL":to};if(to==="QUIRÓFANO")patch["EN QNO"]="TRUE";if(to==="RECUPERACIÓN"){patch["RECUPERACIÓN"]="TRUE";patch["OPERADO"]="TRUE"}const c=await updateCase(s,b.id,patch,"MOVER PACIENTE");await addMovement(s,Object.assign({},hit.payload,patch),from,to);return json(c)}
 if(url.pathname==="/api/case/qno"&&req.method==="POST"){const b=await body(req),q=String(b.qno||"").toUpperCase();if(!["QNO 1","QNO 2","QNO 3"].includes(q))return json({error:"QNO inválido."},400);return json(await updateCase(s,b.id,{"SALA / QNO":q},"CAMBIO QNO"))}
 if(url.pathname==="/api/case/cancel"&&req.method==="POST"){const b=await body(req);if(!String(b.motivo||"").trim())return json({error:"Debe registrar el motivo."},400);const hit=await findCase(b.id);if(!hit)return json({error:"Paciente no encontrado."},404);const c=await updateCase(s,b.id,{"ESTADO ACTUAL":"CANCELADO","CANCELAR":"TRUE","OBSERVACIONES":String(b.motivo).trim()},"CANCELAR PACIENTE");await addMovement(s,Object.assign({},hit.payload,{"ESTADO ACTUAL":"CANCELADO"}),hit.payload["ESTADO ACTUAL"]||"","CANCELADO");return json(c)}
 if(url.pathname==="/api/case/finish"&&req.method==="POST"){const b=await body(req),d=String(b.destino||"").toUpperCase();if(!["ALTA","HOSPITALIZACIÓN"].includes(d))return json({error:"Destino inválido."},400);const c=await updateCase(s,b.id,{"ESTADO ACTUAL":d,"DESTINO POSTOP":d,"HORA SALIDA RECUPERACIÓN":nowBog(),"OBSERVACIÓN EGRESO / HOSPITALIZACIÓN":String(b.observacion||"")},"CIERRE RECUPERACIÓN");return json(c)}
 if(url.pathname==="/api/patient"&&req.method==="POST"){const b=await body(req);if(!b.fecha||!b.hora||!b.documento||!b.paciente||!b.procedimiento)return json({error:"Fecha, hora, documento, paciente y procedimiento son obligatorios."},400);const id="QX-"+String(b.fecha).replace(/-/g,"")+"-"+randomBytes(4).toString("hex").toUpperCase(),track=randomBytes(4).toString("hex").toUpperCase(),token=randomBytes(12).toString("hex");const p={"ID CASO":id,"FECHA CIRUGÍA":safeDate(b.fecha),"HORA PROGRAMADA":String(b.hora).slice(0,5),"DOCUMENTO":String(b.documento).trim(),"PACIENTE":String(b.paciente).trim().toUpperCase(),"EDAD":b.edad||"","SEXO":b.sexo||"","PROCEDIMIENTO":String(b.procedimiento).trim().toUpperCase(),"ESPECIALIDAD":String(b.especialidad||"").trim().toUpperCase(),"ESPECIALISTA":String(b.especialista||"").trim().toUpperCase(),"SALA / QNO":String(b.qno||"").toUpperCase(),"ESTADO ACTUAL":"PROGRAMADO","OBSERVACIONES":b.observaciones||"","TIPO DE ATENCIÓN":b.tipoAtencion||"","CAMA / UBICACIÓN PROGRAMADA":b.cama||"","CUPS":b.cups||"","UVR":b.uvr||"","TIEMPO QX ESTIMADO (MIN)":b.tiempoQx||"","RECURSOS / ALERTAS PREQUIRÚRGICAS":b.recursos||"","CÓDIGO SEGUIMIENTO":track,"TOKEN SEGUIMIENTO":token,"CREADO SEGUIMIENTO":nowBog(),"FUENTE DE PROGRAMACIÓN":"RAILWAY","ÚLTIMA ACTUALIZACIÓN WEB":nowBog()};const rn=await nextRow("BD PROGRAMACIÓN");await sql.unsafe("insert into source_sheets(source_key,spreadsheet_id,spreadsheet_title,sheet_name,row_number,payload) values('MAIN','RAILWAY','Railway operational','BD PROGRAMACIÓN',$1,$2::jsonb)",[rn,JSON.stringify(p)]);await outbox("PACIENTE",id,"CREAR",p);await audit(s,"CREAR PACIENTE","PROGRAMACIÓN",id,"Nuevo paciente");return json({ok:true,id,trackingCode:track,case:mapCase(p)})}
 if(url.pathname==="/api/bulk"&&req.method==="POST"){const b=await body(req),rows=Array.isArray(b.rows)?b.rows:[];if(rows.length>1000)return json({error:"Máximo 1000 filas por cargue."},400);let inserted=0,skipped=0;for(const r of rows){if(!r.fecha||!r.paciente||!r.procedimiento){skipped++;continue}const date=safeDate(r.fecha),dup=await sql.unsafe("select 1 from source_sheets where source_key='MAIN' and sheet_name='BD PROGRAMACIÓN' and payload->>'FECHA CIRUGÍA'=$1 and payload->>'DOCUMENTO'=$2 and upper(payload->>'PROCEDIMIENTO')=$3 limit 1",[date,String(r.documento||""),String(r.procedimiento||"").toUpperCase()]);if(dup.length){skipped++;continue}const id="QX-"+date.replace(/-/g,"")+"-"+randomBytes(4).toString("hex").toUpperCase(),p={"ID CASO":id,"FECHA CIRUGÍA":date,"HORA PROGRAMADA":String(r.hora||"").slice(0,5),"DOCUMENTO":String(r.documento||""),"PACIENTE":String(r.paciente||"").toUpperCase(),"EDAD":r.edad||"","SEXO":r.sexo||"","CUPS":r.cups||"","PROCEDIMIENTO":String(r.procedimiento||"").toUpperCase(),"ESPECIALIDAD":String(r.especialidad||"").toUpperCase(),"ESPECIALISTA":String(r.especialista||"").toUpperCase(),"SALA / QNO":String(r.qno||"").toUpperCase(),"TIPO DE ATENCIÓN":String(r.tipoAtencion||"").toUpperCase(),"CAMA / UBICACIÓN PROGRAMADA":r.cama||"","OBSERVACIONES":r.observaciones||"","ESTADO ACTUAL":"PROGRAMADO","FUENTE DE PROGRAMACIÓN":"CARGUE RAILWAY","CÓDIGO SEGUIMIENTO":randomBytes(4).toString("hex").toUpperCase(),"TOKEN SEGUIMIENTO":randomBytes(12).toString("hex"),"CREADO SEGUIMIENTO":nowBog(),"ÚLTIMA ACTUALIZACIÓN WEB":nowBog()};const rn=await nextRow("BD PROGRAMACIÓN");await sql.unsafe("insert into source_sheets(source_key,spreadsheet_id,spreadsheet_title,sheet_name,row_number,payload) values('MAIN','RAILWAY','Railway operational','BD PROGRAMACIÓN',$1,$2::jsonb)",[rn,JSON.stringify(p)]);await outbox("PACIENTE",id,"CARGUE_MASIVO",p);inserted++}await audit(s,"CARGUE MASIVO","PROGRAMACIÓN","",inserted+" insertados; "+skipped+" omitidos");return json({ok:true,inserted,skipped})}
 if(url.pathname==="/api/profilaxis"){const rows=(await casesFor(url.searchParams.get("date")||"")).filter(x=>x.prof||x.profHora||x.clasif||x.antibiotico),m={total:rows.length,registrada:0,noRegistrada:0,pendiente:0,conMedicamento:0,conTiempo:0};const out=rows.map(x=>({paciente:x.paciente,procedimiento:x.procedimiento,administrada:x.prof,medicamento:x.antibiotico,hora:x.profHora,minutos:x.profMin,clasificacion:x.clasif}));out.forEach(r=>{const a=norm(r.administrada);if(["SI","SÍ"].includes(a))m.registrada++;else if(a==="NO")m.noRegistrada++;else m.pendiente++;if(r.medicamento)m.conMedicamento++;if(String(r.minutos)!=="")m.conTiempo++});return json({rows:out,metrics:m})}
 if(url.pathname==="/api/postop"){const base=(await casesFor(url.searchParams.get("date")||"")).filter(r=>r.operado||["RECUPERACIÓN","ALTA","HOSPITALIZACIÓN"].includes(r.estado)||r.destino),rows=base.map(r=>({paciente:r.paciente,procedimiento:r.procedimiento,estado:r.estado,destino:r.destino,salida:r.salida,observacion:r.observacionEgreso,codigo:r.codigo})),m={total:rows.length,alta:0,hospitalizacion:0,recuperacion:0,conSeguimiento:0,pendientes:0};rows.forEach(r=>{const d=norm(r.destino||r.estado);if(d==="ALTA")m.alta++;if(d==="HOSPITALIZACION")m.hospitalizacion++;if(r.estado==="RECUPERACIÓN")m.recuperacion++;if(r.codigo)m.conSeguimiento++;else m.pendientes++});return json({rows,metrics:m})}
 if(url.pathname==="/api/coord"){const rows=await casesFor(url.searchParams.get("date")||""),m=metrics(rows),by={};rows.forEach(r=>{const k=r.especialidad||"SIN ESPECIALIDAD";if(!by[k])by[k]={especialidad:k,total:0,operados:0,cancelados:0};by[k].total++;if(r.operado)by[k].operados++;if(r.estado==="CANCELADO")by[k].cancelados++});return json({metrics:m,specialties:Object.values(by).sort((a,b)=>b.total-a.total)})}
 if(url.pathname==="/api/kpi"){const date=safeDate(url.searchParams.get("date")||""),period=String(url.searchParams.get("period")||"MES").toUpperCase();let data;if(period==="DIA")data=await casesFor(date);else{const ym=date.slice(0,7);const r=await sql.unsafe("select payload from source_sheets where source_key='MAIN' and sheet_name='BD PROGRAMACIÓN' and left(payload->>'FECHA CIRUGÍA',7)=$1",[ym]);data=r.map(x=>mapCase(x.payload))}const brutas=data.length,canceladas=data.filter(x=>x.estado==="CANCELADO").length,netas=brutas-canceladas,ejecutadas=data.filter(x=>x.operado).length,esp={};data.forEach(r=>{const k=r.especialidad||"SIN ESPECIALIDAD";if(!esp[k])esp[k]={especialidad:k,programadasBrutas:0,canceladas:0,programadasNetas:0,ejecutadas:0,prepa:[],qnoRec:[],muertos:[]};const g=esp[k];g.programadasBrutas++;if(r.estado==="CANCELADO")g.canceladas++;else g.programadasNetas++;if(r.operado)g.ejecutadas++;if(r.tPrepa)g.prepa.push(r.tPrepa);if(r.tQnoRec)g.qnoRec.push(r.tQnoRec);if(r.tMuerto)g.muertos.push(r.tMuerto)});const especialidades=Object.values(esp).map(g=>({especialidad:g.especialidad,programadasBrutas:g.programadasBrutas,canceladas:g.canceladas,programadasNetas:g.programadasNetas,ejecutadas:g.ejecutadas,tasaRealizacion:pct(g.ejecutadas,g.programadasNetas),tasaCancelacion:pct(g.canceladas,g.programadasBrutas),tiempoPrepaQno:avg(g.prepa),tiempoQnoRec:avg(g.qnoRec),tiempoMuerto:avg(g.muertos)})).sort((a,b)=>b.programadasBrutas-a.programadasBrutas);const qs={};data.forEach(r=>{const q=r.qno||"SIN QNO";if(!qs[q])qs[q]={qno:q,t:[],m:[]};if(r.tQnoRec)qs[q].t.push(r.tQnoRec);if(r.tMuerto)qs[q].m.push(r.tMuerto)});const qnos=Object.values(qs).map(q=>({qno:q.qno,tiempoQnoRec:avg(q.t),tiempoMuerto:avg(q.m)}));const causas={};data.filter(x=>x.estado==="CANCELADO").forEach(x=>{const k=x.observaciones||"SIN MOTIVO";causas[k]=(causas[k]||0)+1});return json({summary:{programadasBrutas:brutas,canceladas,programadasNetas:netas,ejecutadas,tasaCancelacion:pct(canceladas,brutas),tasaRealizacion:pct(ejecutadas,netas),tiempoPrepaQno:avg(data.map(x=>x.tPrepa)),tiempoQnoRec:avg(data.map(x=>x.tQnoRec)),tiempoMuerto:avg(data.map(x=>x.tMuerto))},especialidades,qnos,flujo:[{label:"PROGRAMADO",value:data.filter(x=>x.estado==="PROGRAMADO").length},{label:"PREPARACIÓN",value:data.filter(x=>x.estado==="PREPARACIÓN").length},{label:"QUIRÓFANO",value:data.filter(x=>x.estado==="QUIRÓFANO").length},{label:"RECUPERACIÓN",value:data.filter(x=>x.estado==="RECUPERACIÓN").length},{label:"FINALIZADOS",value:data.filter(x=>["ALTA","HOSPITALIZACIÓN"].includes(x.estado)).length},{label:"CANCELADOS",value:canceladas}],cancelaciones:{causas:Object.entries(causas).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)}})}
 if(url.pathname==="/api/mci"){const date=safeDate(url.searchParams.get("date")||""),y=Number(date.slice(0,4)),m=Number(date.slice(5,7)),mes=monthName(m);const sum=await sql.unsafe("select payload from source_sheets where source_key='MAIN' and sheet_name='RESUMEN ANUAL' and payload->>'Mes'=$1 limit 1",[mes]);const base=await sql.unsafe("select payload from source_sheets where source_key='MAIN' and sheet_name=$1 and payload->>'Mes'=$2 order by row_number",["BASE ANUAL "+y,mes]);const x=sum[0]?.payload||{};return json({metrics:{mes,meta:x["Meta"]||"0",programadas:x["Programadas netas"]||"0",ejecutadas:x["Ejecutadas"]||"0",cumplimiento:x["Cumplimiento"]||"—",tasaRealizacion:x["Tasa realización"]||"—",brecha:x["Brecha"]||"0",proyeccion:x["Proyección"]||"—",estado:x["Estado"]||"SIN DATOS"},daily:base.map(z=>{const p=z.payload;return{fecha:p["Fecha"]||"",dia:p["Día"]||"",qxDisponibles:p["Qx disponibles"]||"",metaDiaria:p["Meta diaria"]||"",programadas:p["Cirugías programadas netas"]||"",ejecutadas:p["Cirugías ejecutadas"]||"",cumple:p["Cumple meta diaria"]||"",diferencia:p["Diferencia vs meta diaria"]||"",acumulado:p["Acumulado mensual"]||""}})})}
 if(url.pathname==="/api/reinterventions"){const date=safeDate(url.searchParams.get("date")||""),end=new Date(date+"T12:00:00Z"),start=new Date(end.getTime()-30*86400000),a=start.toISOString().slice(0,10);const r=await sql.unsafe("select payload from source_sheets where source_key='MAIN' and sheet_name='BD PROGRAMACIÓN' and payload->>'FECHA CIRUGÍA'>=$1 and payload->>'FECHA CIRUGÍA'<=$2 order by payload->>'DOCUMENTO',payload->>'FECHA CIRUGÍA'",[a,date]);const list=r.map(x=>mapCase(x.payload)),by={};list.forEach(x=>{if(x.documento)(by[x.documento]||(by[x.documento]=[])).push(x)});const rows=[];Object.values(by).forEach(arr=>{for(let i=1;i<arr.length;i++){const p=arr[i-1],n=arr[i],d=Math.round((new Date(n.fecha)-new Date(p.fecha))/86400000);if(d>=0&&d<30)rows.push({paciente:n.paciente,documento:n.documento,fechaPrevia:p.fecha,fechaNueva:n.fecha,dias:d,especialidad:n.especialidad})}});return json({total:rows.length,reviewed:0,pending:rows.length,rows})}
 if(url.pathname==="/api/download"){const date=safeDate(url.searchParams.get("date")||""),period=String(url.searchParams.get("period")||"DIA").toUpperCase(),type=String(url.searchParams.get("type")||"PROGRAMACION").toUpperCase();let rows;if(period==="MES"){const ym=date.slice(0,7),r=await sql.unsafe("select payload from source_sheets where source_key='MAIN' and sheet_name='BD PROGRAMACIÓN' and left(payload->>'FECHA CIRUGÍA',7)=$1 order by payload->>'FECHA CIRUGÍA',payload->>'HORA PROGRAMADA'",[ym]);rows=r.map(x=>mapCase(x.payload))}else rows=await casesFor(date);if(type==="ACTIVOS")rows=rows.filter(x=>!["ALTA","HOSPITALIZACIÓN","CANCELADO"].includes(x.estado));if(type==="EJECUTADAS")rows=rows.filter(x=>x.operado);if(type==="FINALIZADOS")rows=rows.filter(x=>["ALTA","HOSPITALIZACIÓN"].includes(x.estado));if(type==="CANCELADOS")rows=rows.filter(x=>x.estado==="CANCELADO");if(/^QNO [123]$/.test(type))rows=rows.filter(x=>norm(x.qno)===norm(type));let headers=["Fecha","Hora","Paciente","Documento","Procedimiento","Especialidad","Especialista","QNO","Estado","Tipo atención","Observaciones"],data=rows.map(x=>[x.fecha,x.hora,x.paciente,x.documento,x.procedimiento,x.especialidad,x.especialista,x.qno,x.estado,x.tipoAtencion,x.observaciones]);if(type==="TIEMPOS_QNO"){headers=["Fecha","Hora","Paciente","QNO","Prepa→QNO (min)","QNO→Recuperación (min)","Tiempo muerto QNO (min)"];data=rows.map(x=>[x.fecha,x.hora,x.paciente,x.qno,x.tPrepa,x.tQnoRec,x.tMuerto])}if(type==="PROFILAXIS"){headers=["Fecha","Hora","Paciente","Documento","QNO","Administrada","Medicamento","Hora profilaxis","Minutos a incisión","Clasificación"];data=rows.map(x=>[x.fecha,x.hora,x.paciente,x.documento,x.qno,x.prof,x.antibiotico,x.profHora,x.profMin,x.clasif])}const csv=[headers,...data].map(r=>r.map(csvCell).join(",")).join("\n"),name="Cirugia_"+type.replace(/\s+/g,"_")+"_"+date+".csv";await audit(s,"DESCARGA","REPORTES","",type+" "+period);return new Response("\ufeff"+csv,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":"attachment; filename=\""+name+"\"","x-filename":name,"cache-control":"no-store"}})}
 return json({error:"Not found"},404);
}});
console.log("APP WEB CX Railway 5 operational",PORT);