import catalog from './data/indicator-catalog.json';
import lists from './data/application-lists.json';
export const APPLICATION_DEFAULTS={branding:{title:'Control de Pacientes Quirúrgicos',service:'Flujo quirúrgico del servicio',brand:'AMA',primaryColor:'#44358b',portalRefreshSeconds:15},lists,indicatorMetadata:{},criteria:{appointmentMaxDays:10},sourceKind:'SIMULADO'};
export async function initApplicationSettings(sql){
 await sql.unsafe(`create schema if not exists qx_simulation;create table if not exists qx_simulation.qx_application_settings(id text primary key,version integer not null default 1,payload jsonb not null);create table if not exists qx_simulation.qx_application_settings_history(id text primary key,payload jsonb not null,created_at timestamptz not null default now())`);
 await sql.unsafe("insert into qx_simulation.qx_application_settings(id,payload) values('PAGE',$1::jsonb) on conflict(id) do nothing",[JSON.stringify(APPLICATION_DEFAULTS)]);
}
export async function readApplicationSettings(sql){const rows=await sql.unsafe("select version,payload from qx_simulation.qx_application_settings where id='PAGE'");const p=rows[0]?.payload||{};return {version:Number(rows[0]?.version||1),config:{...APPLICATION_DEFAULTS,...p,branding:{...APPLICATION_DEFAULTS.branding,...p.branding},lists:{...lists,...p.lists},criteria:{...APPLICATION_DEFAULTS.criteria,...p.criteria},indicatorMetadata:p.indicatorMetadata||{}}};}
export function indicatorDefinitions(config){return {...catalog,metrics:catalog.metrics.map(item=>({...item,...config.indicatorMetadata?.[item.id],calculationFormula:['PASP_APPOINTMENT_TIMELINESS','PASP_APPOINTMENT_LATE','PASP_APPOINTMENT_OVERDUE_WITHOUT_DATE'].includes(item.id)?item.formula.replace(/10/g,String(config.criteria?.appointmentMaxDays||10)):item.formula}))};}
export function validateApplicationSettings(input){
 const p=structuredClone(input);if(!p||typeof p!=='object'||Array.isArray(p))throw Error('Configuración inválida.');
 const b=p.branding||{};for(const key of ['title','service','brand'])if(typeof b[key]!=='string'||!b[key].trim()||b[key].length>160)throw Error('Revise los textos de presentación.');
 if(!/^#[0-9a-f]{6}$/i.test(b.primaryColor||''))throw Error('El color debe usar formato #RRGGBB.');
 if(!Number.isInteger(Number(b.portalRefreshSeconds))||Number(b.portalRefreshSeconds)<5||Number(b.portalRefreshSeconds)>300)throw Error('La actualización debe estar entre 5 y 300 segundos.');
 b.portalRefreshSeconds=Number(b.portalRefreshSeconds);p.branding=b;
 if(!p.lists||typeof p.lists!=='object'||Array.isArray(p.lists))throw Error('Listas inválidas.');
 for(const [key,values] of Object.entries(p.lists)){if(!Object.hasOwn(lists,key)||!Array.isArray(values)||values.length>250||values.some(v=>typeof v!=='string'||!v.trim()||v.length>180)||new Set(values.map(v=>v.toLocaleLowerCase('es'))).size!==values.length)throw Error('Revise la lista '+key);}
 const allowed=new Set(catalog.metrics.map(m=>m.id));
 for(const [key,value] of Object.entries(p.indicatorMetadata||{})){if(!allowed.has(key)||!value||typeof value!=='object'||Array.isArray(value))throw Error('Indicador inválido.');for(const k of Object.keys(value))if(!['label','goal','definition','frequency','owner'].includes(k))throw Error('El cálculo y denominador no se cambian al editar una ficha técnica.');for(const v of Object.values(value))if(typeof v!=='string'||v.length>2500)throw Error('Texto de indicador inválido.');}
 const max=Number(p.criteria?.appointmentMaxDays);if(!Number.isInteger(max)||max<1||max>365)throw Error('El plazo de cita POP debe estar entre 1 y 365 días.');p.criteria={appointmentMaxDays:max};p.sourceKind='SIMULADO';return p;
}
export const PROPHYLAXIS_FIELDS=['ESPECIALIDAD','PROCEDIMIENTO','TÉRMINOS SIMILARES / SINÓNIMOS','ANTIBIÓTICO PRIMERA ELECCIÓN','DOSIS ADULTO','MOMENTO ADMINISTRACIÓN','AJUSTES / CONSIDERACIONES','FUENTE DOCUMENTAL','VERSIÓN','DILUCIÓN (FARMACIA)','ADMINISTRACIÓN (FARMACIA)','INTERACCIONES (FARMACIA)','EFECTOS ADVERSOS (FARMACIA)'];
export async function handleProphylaxisConfiguration(req,url,ctx){
 if(url.pathname!=='/api/prophylaxis-rules')return null;
 if(ctx.session?.role!=='SUPERADMIN')return ctx.json({error:'El catálogo institucional requiere SUPERADMIN.'},403);
 if(req.method==='GET'){const rows=await ctx.sql.unsafe('select row_order,payload from qx_simulation.qx_prophylaxis_rules order by row_order');return ctx.json({rows:rows.map(r=>({rowOrder:r.row_order,...r.payload})),fields:PROPHYLAXIS_FIELDS,sourceKind:'SIMULADO'});}
 if(req.method!=='POST')return ctx.json({error:'Acción no disponible.'},405);
 try{const b=await req.json(),p={};if(!b.reason?.trim())throw Error('Registre motivo y autoridad del cambio.');for(const key of PROPHYLAXIS_FIELDS)p[key]=String(b.rule?.[key]||'').trim().slice(0,5000);if(!p.PROCEDIMIENTO||!p.ESPECIALIDAD)throw Error('Procedimiento y especialidad son obligatorios.');p.ESTADO=b.rule.ESTADO==='ACTIVO'?'ACTIVO':'INACTIVO';p.APROBACION=b.rule.APROBACION==='REVISADO'?'REVISADO':'PENDIENTE';if(p.ESTADO==='ACTIVO'&&(p.APROBACION!=='REVISADO'||!p['FUENTE DOCUMENTAL']||!p['VERSIÓN']))throw Error('Para activar una regla documente revisión institucional, fuente y versión.');
 const result=await ctx.sql.begin(async tx=>{const existing=b.rowOrder?await tx.unsafe('select payload from qx_simulation.qx_prophylaxis_rules where row_order=$1 for update',[Number(b.rowOrder)]):[];if(b.rowOrder&&!existing.length)throw Error('Regla no encontrada.');const previous=existing[0]?.payload;if(previous&&Number(b.expectedVersion)!==Number(previous['VERSIÓN CONFIG']||1))throw Error('La regla cambió. Actualice antes de guardar.');p['ID REGLA']=previous?.['ID REGLA']||'SIM-PROF-'+crypto.randomUUID();p['VERSIÓN CONFIG']=Number(previous?(previous['VERSIÓN CONFIG']||1):0)+1;p['ACTUALIZADO POR']=ctx.session.user;p['ACTUALIZADO EN']=new Date().toISOString();const rowOrder=Number(b.rowOrder)||(Number((await tx.unsafe('select coalesce(max(row_order),0) as n from qx_simulation.qx_prophylaxis_rules'))[0].n)+1);await tx.unsafe(previous?'update qx_simulation.qx_prophylaxis_rules set payload=$2::jsonb,updated_at=now() where row_order=$1':'insert into qx_simulation.qx_prophylaxis_rules(row_order,payload) values($1,$2::jsonb)',[rowOrder,JSON.stringify(p)]);await tx.unsafe('insert into qx_simulation.qx_application_settings_history(id,payload) values($1,$2::jsonb)',[crypto.randomUUID(),JSON.stringify({area:'PROFILAXIS',rowOrder,previous,updated:p,author:ctx.session.user,reason:b.reason,sourceKind:'SIMULADO'})]);return {rowOrder,...p};});return ctx.json({ok:true,rule:result});
 }catch(e){return ctx.json({error:e.message||'Revise la regla.'},400);}
}
export async function handleApplicationSettings(req,url,ctx){
 if(!['/api/application-settings','/api/application-settings/public','/api/indicator-definitions'].includes(url.pathname))return null;
 if(url.pathname==='/api/application-settings/public'&&req.method==='GET'){const data=await readApplicationSettings(ctx.sql);return ctx.json({branding:data.config.branding,sourceKind:'SIMULADO'});}
 if(!ctx.session)return ctx.json({error:'Sesión no autorizada.'},401);
 if(req.method==='GET'){const data=await readApplicationSettings(ctx.sql);if(url.pathname==='/api/indicator-definitions')return ctx.json(indicatorDefinitions(data.config));return ctx.json(data);}
 if(req.method!=='POST'||url.pathname!=='/api/application-settings')return ctx.json({error:'Acción no disponible.'},405);
 if(ctx.session.role!=='SUPERADMIN')return ctx.json({error:'La configuración general requiere SUPERADMIN.'},403);
 try{const b=await req.json();if(!String(b.reason||'').trim())return ctx.json({error:'Registre el motivo del cambio.'},400);const next=validateApplicationSettings(b.config);
 const result=await ctx.sql.begin(async tx=>{const rows=await tx.unsafe("select version,payload from qx_simulation.qx_application_settings where id='PAGE' for update");if(Number(b.expectedVersion)!==Number(rows[0].version))return {conflict:true};const version=Number(rows[0].version)+1;await tx.unsafe("update qx_simulation.qx_application_settings set version=$1,payload=$2::jsonb where id='PAGE'",[version,JSON.stringify(next)]);await tx.unsafe("insert into qx_simulation.qx_application_settings_history(id,payload) values($1,$2::jsonb)",[crypto.randomUUID(),JSON.stringify({version,previousVersion:rows[0].version,reason:String(b.reason).slice(0,2000),author:ctx.session.user,changedAt:new Date().toISOString(),changedAreas:Object.keys(next),sourceKind:'SIMULADO'})]);return {config:next,version};});
 if(result.conflict)return ctx.json({error:'Otra persona cambió la configuración. Actualice antes de guardar.'},409);return ctx.json({ok:true,...result});
 }catch(error){return ctx.json({error:error.message||'Revise la configuración.'},400);}
}
